# NG4 Fitrasari

In [2]:
import numpy as np

# Nomor 1


**Buat Tensor dengan python dengan data [[[23,50],[7,12]],[[57,67],[99,43]],[[75,21],[57,12]],[[87,26],[18,84]]]**

In [3]:
T = np.array([[[23,50],[7,12]],[[57,67],[99,43]],[[75,21],[57,12]],[[87,26],[18,84]]])

In [4]:
T.shape

(4, 2, 2)

In [5]:
T

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

# Nomor 2

**Cari hasil perkalian dari A dan B.** 

**A = np.array([[23,50,19],[7,12,109],[57,57,98]])**

**B = np.array([[17],[12],[19]])**

In [6]:
A = np.array([[23,50,19],[7,12,109],[57,57,98]])
B = np.array([[17],[12],[19]])

print(A)
print(A.shape)
print(B)
print(B.shape)

[[ 23  50  19]
 [  7  12 109]
 [ 57  57  98]]
(3, 3)
[[17]
 [12]
 [19]]
(3, 1)


In [14]:
A * B

array([[ 391,  850,  323],
       [  84,  144, 1308],
       [1083, 1083, 1862]])

# Nomor 3

**Cari Transpose, Determinan, dan Invers dari A. A = np.array([[23,50,19],[7,12,109],[57,57,98]])**

*Transpose A*

In [9]:
TransA = A.T
TransA

array([[ 23,   7,  57],
       [ 50,  12,  57],
       [ 19, 109,  98]])

*Determinan A*

In [10]:
from numpy.linalg import det

In [11]:
deterA = det(A)
deterA

155084.0000000002

*Inverse A*

In [12]:
from numpy.linalg import inv

In [13]:
inverA = inv(A)
inverA

array([[-0.03247917, -0.02461247,  0.03367207],
       [ 0.03563875,  0.00755075, -0.01530783],
       [-0.00183771,  0.00992365, -0.00047716]])